name: muebleria_zarate
description: "AplicaciÃ³n Flutter para la MueblerÃ­a ZÃ¡rate"
publish_to: 'none'

version: 1.5.3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¹ Firebase (solo lo necesario para tu app)
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

  # ğŸ”¹ UI y utilidades
  cached_network_image: ^3.2.3
  email_validator: ^2.0.1
  http: ^1.1.0

  google_maps_flutter: ^2.7.0
  location: ^6.0.2

  url_launcher: ^6.2.5

  # ğŸ”¹ Animaciones Lottie
  lottie: ^2.7.0
  image_picker: ^1.0.4
  
  # ğŸ”¹ GeneraciÃ³n de PDF para notas de venta
  pdf: ^3.10.7
  
  # ğŸ”¹ EnvÃ­o de correos vÃ­a SMTP
  mailer: ^6.1.2
  
  # ğŸ”¹ Acceso a directorios temporales
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # ğŸ”¹ Iconos y splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon1.png"               # â† CORREGIDO
  adaptive_icon_background: "#D2B48C"
  adaptive_icon_foreground: "assets/icons/icon.png" # â† CORREGIDO

flutter_native_splash:
  color: "#CBB59E"
  image: assets/icons/icon.png                      # â† CORREGIDO
  android: true
  ios: true
  android_12:
    icon_background_color: "#CBB59E"
    image: assets/icons/icon.png                    # â† CORREGIDO
