name: muebleria_zarate
description: "AplicaciÃ³n Flutter para la MueblerÃ­a ZÃ¡rate"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¹ Firebase (solo lo necesario para tu app)
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  # ğŸ”¹ UI y utilidades
  cached_network_image: ^3.2.3
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
